In [1]:
import numpy as np

#1-D array
d = np.array([1,2,3])
type(d)

numpy.ndarray

In [2]:
d

array([1, 2, 3])

In [3]:
#multi dimensional array
nd = np.array([[1,2,3], [3,4,5], [10,11,12]])
type(nd)

numpy.ndarray

In [4]:
nd

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [10, 11, 12]])

In [5]:
nd.shape #shape of array

(3, 3)

In [6]:
nd.dtype #data type

dtype('int32')

In [7]:
#define zero matrix
np.zeros(3) 

array([0., 0., 0.])

In [9]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
#diagonal matrix
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
#add 2 to e
e2 = e+2

In [14]:
e2

array([[3., 2., 2.],
       [2., 3., 2.],
       [2., 2., 3.]])

In [25]:
#create matrix with all entries as 1 and size as 'e2'
o = np.ones_like(e2)
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
#changing data type
o.dtype

dtype('float64')

In [27]:
oi = o.astype(np.int32)
oi

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [30]:
oi.dtype

dtype('int32')

In [31]:
#convert string-list to float
a = ['1', '2', '3']
a_arr = np.array(a, dtype=np.string_) #convert list to ndarray
af = a_arr.astype(float) #change ndarray type
af

array([1., 2., 3.])

In [33]:
af.dtype

dtype('float64')