In [1]:
import numpy as np

#accessing data with boolean indexing
data = np.random.randn(5, 3)
data

array([[ 0.86278549, -0.04987675, -1.12066231],
       [-0.88790574,  1.26591978, -0.85284753],
       [ 0.25014169,  2.03287678,  0.32832499],
       [-0.11467759,  0.27322261,  0.89142016],
       [-2.37101634, -0.07599534, -0.01546114]])

In [2]:
name = np.array(['a', 'b', 'c', 'a', 'b'])
name == 'a'

array([ True, False, False,  True, False])

In [3]:
data[name == 'a']

array([[ 0.86278549, -0.04987675, -1.12066231],
       [-0.11467759,  0.27322261,  0.89142016]])

In [4]:
data[name != 'a']

array([[-0.88790574,  1.26591978, -0.85284753],
       [ 0.25014169,  2.03287678,  0.32832499],
       [-2.37101634, -0.07599534, -0.01546114]])

In [5]:
data [(name == 'b') | (name == 'c')]

array([[-0.88790574,  1.26591978, -0.85284753],
       [ 0.25014169,  2.03287678,  0.32832499],
       [-2.37101634, -0.07599534, -0.01546114]])

In [6]:
data[(data>1) & (data<2)]

array([1.26591978])