In [2]:
import numpy as np

arr = np.arange(12).reshape(3,4)
rn = np.random.randn(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
rn

array([[ 0.69617552,  0.14879889, -0.36446753,  1.17493055],
       [-0.44434084, -0.45590624,  1.91582742, -2.05334393],
       [ 1.85718273, -0.36531524,  2.24778014,  0.43523401]])

In [4]:
#merge the data of rn below the arr
np.concatenate([arr, rn])

array([[ 0.        ,  1.        ,  2.        ,  3.        ],
       [ 4.        ,  5.        ,  6.        ,  7.        ],
       [ 8.        ,  9.        , 10.        , 11.        ],
       [ 0.69617552,  0.14879889, -0.36446753,  1.17493055],
       [-0.44434084, -0.45590624,  1.91582742, -2.05334393],
       [ 1.85718273, -0.36531524,  2.24778014,  0.43523401]])

In [5]:
#merge data of rn on the rigth side of arr
np.concatenate([arr, rn], axis=1)

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  0.69617552,
         0.14879889, -0.36446753,  1.17493055],
       [ 4.        ,  5.        ,  6.        ,  7.        , -0.44434084,
        -0.45590624,  1.91582742, -2.05334393],
       [ 8.        ,  9.        , 10.        , 11.        ,  1.85718273,
        -0.36531524,  2.24778014,  0.43523401]])